version: '3.8'
services:
  backend:
    build: ./docker/backend
    volumes:
      - ./apps/backend:/app
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
  frontend:
    build: ./docker/frontend
    volumes:
      - ./apps/frontend:/app
    ports:
      - "3000:3000"
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollama_data:
